apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express-web
  template:
    metadata:
      labels:
        app: express-web
    spec:
      containers:
      - name: express-web
        image: gcr.io/olivealex/express-web
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: express-web-service
  labels:
    app: express-web
spec:
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
  selector:
    app: express-web
  type: LoadBalancer